# Generated by Django 2.2.4 on 2019-08-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operation', models.CharField(choices=[('created', 'created'), ('updated', 'updated'), ('deleted', 'deleted')], max_length=20)),
                ('label_name', models.CharField(max_length=255)),
                ('class_short_name', models.CharField(max_length=255)),
                ('pk_value', models.BigIntegerField()),
                ('data', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
